### ISSUE TITLE
Color tag issue

### ISSUE THREAD

**Issue by jakesullyneytiri** [InfernoGroupUK/LayerBulletin#2]
Hey,

Whenever i type any color starting with letter P by doing [color=Purple]example[/color] it shows up as urple">example instead of showing the color :/ so far only letter P is causing this while rest is fine but if i knock into more color's that does the same i will leave reply with them to.

**Comment by InfernoGroupUK** [comment]
I can confirm that this is only happening with the color bbcode when a colour starts with the letter "P".

**Comment by InfernoGroupUK** [comment]
I have not been able to fix this bug so far, I will leave this open for now.

**Comment by InfernoGroupUK** [comment]
This issue does not occur when using the purple hex code, which by the way is "#2E0854".
