### ISSUE TITLE
Recaptcha failed in SSL

### ISSUE THREAD

**Issue by CrunchDrop** [InfernoGroupUK/LayerBulletin#4]
This is on the support board. The recaptcha API doesn't seem to load in a SSL environment.

![0023capture](https://cloud.githubusercontent.com/assets/22418310/23491764/a034d196-febd-11e6-8fcf-b55d8fdebd6f.PNG)

![0034capture](https://cloud.githubusercontent.com/assets/22418310/23491775/a6ad9ada-febd-11e6-943b-d9390266ce58.PNG)

**Comment by InfernoGroupUK** [comment]
Thank you for reporting this.
Could you tell us the steps it took for you to reach this error so that we can reproduce it for ourselves, this way we can look into fixing the issue.

**Comment by InfernoGroupUK** [comment]
I am closing this issue has I have not received any feedback regarding it. 

If you are still having issues, please feel free to open a new issue.

Thank you.

**Comment by InfernoGroupUK** [comment]
Sorry, I have just found the issue. It is fixed on the LayerBulletin Community and will patch this in the latest version.

**Comment by InfernoGroupUK** [comment]
FIXED.
